spring.application.name=taskmanager

# Database Setup (Will be overridden by Kubernetes variables in production)
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=yoursecurepassword

# 🚀 CHANGED THIS LINE TO POSTGRESQL DIALECT
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable H2 console as it is not used in production
spring.h2.console.enabled=false

server.port=8080
